### ISSUE TITLE
Fix date serialization

### ISSUE THREAD

**Issue by aalonsolopez** [Gravitate-Health/summary-lens-service#1]
The date is currently being automatically serialized due to the jsonify() function from Flask. Try to find a solution so @jkiddo can use it.

**Comment by aalonsolopez** [comment]
@jkiddo try now!

**Comment by aalonsolopez** [comment]
Date has this format
![imagen](https://github.com/Gravitate-Health/summary-lens-service/assets/49404378/83bd8029-a7c9-4697-9ad8-d388842f7958)

**Comment by jkiddo** [comment]
this seems wrong:
`"div": "\u003cdiv xmlns\u003d\"http://www.w3.org/1999/xhtml\"\u003e\u003cp\u003eEl medicamento Dovato 50`

**Comment by jkiddo** [comment]
that part might be okay ... but I now see this:

`ca.uhn.fhir.parser.DataFormatException: HAPI-1821: [element="date"] Invalid attribute value "2024-06-03 15:36:10.374713": Invalid date/time format: "2024-06-03 15:36:10.374713": Expected character 'T' at index 10 but found  `

**Comment by aalonsolopez** [comment]
okay i should check the date format that FHIR needs. I remember that you show me.

**Comment by aalonsolopez** [comment]
> this seems wrong: `"div": "\u003cdiv xmlns\u003d\"http://www.w3.org/1999/xhtml\"\u003e\u003cp\u003eEl medicamento Dovato 50`

regarding this, i will check. maybe due to ISO format

**Comment by jkiddo** [comment]
The dateformat is this: https://www.hl7.org/Fhir/datatypes.html#dateTime

**Comment by aalonsolopez** [comment]
Try now! dateformat should be working
`"date": "2024-06-03T15:59:33.284375",`

the div issue is curious because for me, it is working well
![imagen](https://github.com/Gravitate-Health/summary-lens-service/assets/49404378/4eea48a7-10bf-47e1-adca-22d9797055fb)

**Comment by aalonsolopez** [comment]
If date still not working, I have another bullet in the chamber ready 😃. In addition, maybe you are interpreting the string with a wrong encoding? It should be UTF-8 I guess

**Comment by jkiddo** [comment]
works

**Comment by aalonsolopez** [comment]
👏🏻

**Comment by jkiddo** [comment]
now what is left is to get the fix from @joofio on the conditions part
